dat =  ({
    "type": "FeatureCollection",
    "name": "Recreation_Opportunities_(Feature_Layer)",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": [
    { "type": "Feature", "properties": { "RECAREANAME": "River Road Seedbeds", "LONGITUDE": "-88.171564", "LATITUDE": "41.341328", "RECAREAURL": "https://www.fs.usda.gov/recarea/midewin/recarea/?recid=57094", "OPEN_SEASON_START": "January 1", "OPEN_SEASON_END": "December 31", "FORESTNAME": "Midewin National Tallgrass Prairie", "RECAREAID": 57094, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016636.png", "MARKERACTIVITY": "Viewing Plants", "MARKERACTIVITYGROUP": "Nature Viewing", "RECAREADESCRIPTION": "<p>Like most of Illinois, very little of Midewin consists of natural prairie &ndash; less than 200 acres, scattered in little remnants across the site. To restore the remainder of Midewin to tallgrass prairie and other native habitats (nearly 20,000 acres) will take considerable time and plant materials, including seed.</p><p>Three seedbeds, at the Supervisor&rsquo;s Office, River Road and Chicago Road, provide the native plant seeds from over 100 species of prairie plants to help restore Midewin with native plants.</p><p><strong>River Road: </strong>There is a parking area available near these seedbeds, located north of River Road along Boathouse Road. This is a wetland species seedbed.</p><p>Although some types of wild seed are available from specialized native plant nurseries, many are not. That&rsquo;s one major purpose of Midewin&rsquo;s three native seed production gardens -- to produce seeds of native grasses and wildflowers that we cannot get from other sources. Many of these plant species are not commercially available, or if available, not in the amounts we need to restore prairie to Midewin. Even with our own production of seed and plants, it will still take many decades to restore much of the native habitats to Midewin.</p><p>For more information on seed production and some <a href=\"https://www.fs.usda.gov/detail/midewin/landmanagement/resourcemanagement/?cid=STELPRDB5176370\">Frequently Asked Questions </a> visit the Land And Resources Management section of the website.</p>", "RECPORTAL_UNIT_KEY": "57092", "FORESTORGCODE": "0915", "OBJECTID": 37682785, "FEEDESCRIPTION": "This is not a fee site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "open" }, "geometry": { "type": "Point", "coordinates": [ -88.17156985582686, 41.34133573116096 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Welcome Center", "LONGITUDE": "-88.132912", "LATITUDE": "41.343190", "RECAREAURL": "https://www.fs.usda.gov/recarea/midewin/recarea/?recid=57096", "OPEN_SEASON_START": "January 1", "OPEN_SEASON_END": "December 31", "FORESTNAME": "Midewin National Tallgrass Prairie", "RECAREAID": 57096, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016805.png", "MARKERACTIVITY": "Visitor Centers", "MARKERACTIVITYGROUP": "Outdoor Learning", "RECAREADESCRIPTION": "<p>Midewin Welcome Center offers a tranquil space with pleasant nature sounds on a recording with colorful interpretive signs that highlight the cultural and natural history of the land. Visitors to the Welcome Center will find out more about Midewin&#39;s history and mission and how restoration is occurring.</p><p>Those coming to learn about or view the Bison will want to start here to find out more about the Bison Project and explore the bison boxes. There are several displays at the Welcome Center, including Glaciers, Wetland Habitats, Prairie Habitats, Wildlife that Inhabit Wetlands and Prairies, Ghosts of the Prairie and the Timeline of the Midewin Area. The Welcome Center has a variety of programs and tours from April to October. During the winter months we host a &quot;Winter Lecture Series&quot; on nature and conservation related topics, held in the conference room.</p><p>Scroll down to &quot;Visitor Programs&quot; for event schedules, program and volunteer day information and, during winter months, the winter lecture series information.</p>", "RECPORTAL_UNIT_KEY": "57092", "FORESTORGCODE": "0915", "OBJECTID": 37682786, "FEEDESCRIPTION": "This is not a fee site.", "OPERATIONAL_HOURS": "Mon - Sat: 8:00 a.m. to 4:30 p.m. <strong><em>May to October</em></strong><br />Mon - Fri: 8:00 a.m. to 4:30 p.m.&nbsp;<strong><em>November to April</em></strong>", "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "Y", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "open" }, "geometry": { "type": "Point", "coordinates": [ -88.132917844724531, 41.343197733619398 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Hoff Road Trailhead", "LONGITUDE": "-88.077602", "LATITUDE": "41.393737", "RECAREAURL": "https://www.fs.usda.gov/recarea/midewin/recarea/?recid=57098", "OPEN_SEASON_START": "January 1", "OPEN_SEASON_END": "December 31", "FORESTNAME": "Midewin National Tallgrass Prairie", "RECAREAID": 57098, "MARKERTYPE": "/Internet/FSE_MEDIA/stelprdb5175876.png", "MARKERACTIVITY": "Trailhead", "MARKERACTIVITYGROUP": "Trailhead", "RECAREADESCRIPTION": "<p>The Hoff Road Trailhead provides direct access to several trails and areas:</p><ul><li>Twin Oaks Trail</li><li>Old Chicago Road</li><li>Turtle Pond (picnic area)</li><li>Chicago Road Seedbed, (native Illinois seeds)</li><li>Bailey Bridge Trail</li><li>Hedgeapple Trail</li><li>Wauponsee Glacial Trail (Forest Preserve District of Will County&rsquo;s)</li></ul>", "RECPORTAL_UNIT_KEY": "57092", "FORESTORGCODE": "0915", "OBJECTID": 37682787, "FEEDESCRIPTION": "This is not a fee site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "open" }, "geometry": { "type": "Point", "coordinates": [ -88.077607833489935, 41.393744745415596 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Iron Bridge Trailhead", "LONGITUDE": "-88.127057", "LATITUDE": "41.378575", "RECAREAURL": "https://www.fs.usda.gov/recarea/midewin/recarea/?recid=57100", "OPEN_SEASON_START": "January 1", "OPEN_SEASON_END": "December 31", "FORESTNAME": "Midewin National Tallgrass Prairie", "RECAREAID": 57100, "MARKERTYPE": "/Internet/FSE_MEDIA/stelprdb5175876.png", "MARKERACTIVITY": "Trailhead", "MARKERACTIVITYGROUP": "Trailhead", "RECAREADESCRIPTION": "<p>The Iron Bridge Trailhead provides direct access to several trails and areas:</p><ul><li>Route 53 Trail</li><li>Group 63 Trail</li><li>Henslow Trail</li></ul><p><br />Adjacent to the Iron Bridge Trailhead is Midewin&rsquo;s second largest restoration prairie. This Trailhead currently provides the only connection between the East and West side trails via the Henslow Trail.</p><p>Pollinator gardens are located between the parking lot and the trailhead. After exiting your vehicle you can take a short pathway through the pollinator garden before arriving at the information kiosk at the trailhead. About 50 feet from the trailhead the main trail splits to the left and there is a sign that says &quot;To the Campfire Ring,&quot;&nbsp;the trail leads about 100 yards and ends at the Campfire Ring.</p><p>Near the trailhead, there is a heritage farm area where the Rodgers and Shumacher families farmed. The Rodgers farmstead was located just north of the main entrance to the trailhead, and Rodgers farm was located along the north edge of the path leading to the fire ring.</p><p><a href=\"https://midewin.oncell.com/en/200-rodgersschumacher-farmstead-182729.html\">Take a self-guided interpretive tour of this historic area on your mobile device</a>.&nbsp;</p><p>&nbsp;</p>", "RECPORTAL_UNIT_KEY": "57092", "FORESTORGCODE": "0915", "OBJECTID": 37682788, "FEEDESCRIPTION": "This is not a fee site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "open" }, "geometry": { "type": "Point", "coordinates": [ -88.127062846460746, 41.378582740060736 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Explosives Road Trailhead", "LONGITUDE": "-88.134341", "LATITUDE": "41.367685", "RECAREAURL": "https://www.fs.usda.gov/recarea/midewin/recarea/?recid=57102", "OPEN_SEASON_START": "January 1", "OPEN_SEASON_END": "December 31", "FORESTNAME": "Midewin National Tallgrass Prairie", "RECAREAID": 57102, "MARKERTYPE": "/Internet/FSE_MEDIA/stelprdb5175876.png", "MARKERACTIVITY": "Trailhead", "MARKERACTIVITYGROUP": "Trailhead", "RECAREADESCRIPTION": "<p>The Explosives Road Trailhead provides access to the 1.6 mile Newton Loop&nbsp;trail. This is a great bird watching area for Henslow sparrows, loggerhead shrikes, bobolinks, eastern meadowlarks, and dickcissels.</p>", "RECPORTAL_UNIT_KEY": "57092", "FORESTORGCODE": "0915", "OBJECTID": 37682789, "FEEDESCRIPTION": "This is not a fee site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "open" }, "geometry": { "type": "Point", "coordinates": [ -88.134346847526686, 41.367692737775762 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "River Road Trailhead", "LONGITUDE": "-88.171564", "LATITUDE": "41.341328", "RECAREAURL": "https://www.fs.usda.gov/recarea/midewin/recarea/?recid=57104", "OPEN_SEASON_START": "January 1", "OPEN_SEASON_END": "December 31", "FORESTNAME": "Midewin National Tallgrass Prairie", "RECAREAID": 57104, "MARKERTYPE": "/Internet/FSE_MEDIA/stelprdb5175876.png", "MARKERACTIVITY": "Trailhead", "MARKERACTIVITYGROUP": "Trailhead", "RECAREADESCRIPTION": "<p>The River Road Trailhead provides direct access to several trails and areas:</p><ul><li>Prairie Creek Woods Trail</li><li>Buttonbush Pond</li><li>River Road Seedbeds</li><li>South Patrol Road Prairie Restoration</li></ul><p>&nbsp;</p><p>To access the trails from the River Road Trailhead, visitors must first exit the deer fence that surrounds the parking area and seed beds. A pedestrian gate is provided at the north end of the parking lot.</p>", "RECPORTAL_UNIT_KEY": "57092", "FORESTORGCODE": "0915", "OBJECTID": 37682790, "FEEDESCRIPTION": "This is not a fee site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "open" }, "geometry": { "type": "Point", "coordinates": [ -88.17156985582686, 41.34133573116096 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Buttonbush Pond Overlook", "LONGITUDE": "-88.171564", "LATITUDE": "41.341328", "RECAREAURL": "https://www.fs.usda.gov/recarea/midewin/recarea/?recid=57106", "OPEN_SEASON_START": "January 1", "OPEN_SEASON_END": "December 31", "FORESTNAME": "Midewin National Tallgrass Prairie", "RECAREAID": 57106, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016912.png", "MARKERACTIVITY": "Viewing Wildlife", "MARKERACTIVITYGROUP": "Nature Viewing", "RECAREADESCRIPTION": "<p>Buttonbush Pond, is a pond that is home to a variety of frogs and turtles, along with beavers and the occasional egret or duck. Occasionally there will be fish in the pond, but in drier years the pond will dry up. It is surrounded by oak and hickory forest and can be reached by hiking the Prairie Creek Woods Trail.</p><p>Both along the trail and at the pond visitors will be treated to views of several reintroduced native species of wildflower, grass, sedge and rushes. At the overlook to the pond a bench provides respite from the hike, and provides visitors the chance to sit quietly for a few minutes, or hours, to listen to the croaking of the many green frogs that inhabit the area and watch the dragonflies and damselflies flit around.</p><p>&nbsp;</p><p>It isn&rsquo;t known if the pond is naturally occurring or man-made, although evidence of the topography suggests man-made. Because of its location, the water in the pond doesn&rsquo;t come from Prairie Creek, but instead comes from rain and infrequent flooding. As a result the nutrient rich water in the pond is covered in algae during July and August.</p><p>&nbsp;</p>", "RECPORTAL_UNIT_KEY": "57092", "FORESTORGCODE": "0915", "OBJECTID": 37682791, "FEEDESCRIPTION": "This is not a fee site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "open" }, "geometry": { "type": "Point", "coordinates": [ -88.17156985582686, 41.34133573116096 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Turtle Pond", "LONGITUDE": "-88.077602", "LATITUDE": "41.393737", "RECAREAURL": "https://www.fs.usda.gov/recarea/midewin/recarea/?recid=57108", "OPEN_SEASON_START": "January 1", "OPEN_SEASON_END": "December 31", "FORESTNAME": "Midewin National Tallgrass Prairie", "RECAREAID": 57108, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016712.png", "MARKERACTIVITY": "Viewing Wildlife", "MARKERACTIVITYGROUP": "Nature Viewing", "RECAREADESCRIPTION": "<p>A mowed grass trail circles Turtle Pond for a short 0.3-mile walk. In and around the pond visitors will hear and see many types of wildlife, frogs, turtles and birds; along with butterflies, damselflies and dragonflies.</p><p>The nearby Chicago Road Seedbeds, fenced in to try and protect them from deer browsing, provide a riot of color in the spring, summer and even into fall as the native plants begin to bloom, preparing the seeds that Midewin employees will harvest to help restore the 20,000 acre prairie.</p><p>The pond has few ammenities, but visitors will find picnic tables and equestrian users will find tie-ups available for their horses.</p>", "RECPORTAL_UNIT_KEY": "57092", "FORESTORGCODE": "0915", "OBJECTID": 37682792, "FEEDESCRIPTION": "This is not a fee site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "open" }, "geometry": { "type": "Point", "coordinates": [ -88.077607833489935, 41.393744745415596 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "South Patrol Road Prairie Restoration", "LONGITUDE": "-88.171564", "LATITUDE": "41.341328", "RECAREAURL": "https://www.fs.usda.gov/recarea/midewin/recarea/?recid=82169", "OPEN_SEASON_START": "January 1", "OPEN_SEASON_END": "December 31", "FORESTNAME": "Midewin National Tallgrass Prairie", "RECAREAID": 82169, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016882.png", "MARKERACTIVITY": "Viewing Plants", "MARKERACTIVITYGROUP": "Nature Viewing", "RECAREADESCRIPTION": "<p>In the 500-acre South Patrol Road prairie restoration nearly 200 different plant species have been planted and visitors will see sections of 8-foot-tall prairie grasses. The area is a mix of prairie and wetlands. Grassland bird species to see/hear include meadowlarks, bobolinks, dickcissels. Frogs to see and hear include leopard frog, chorus frogs, American Toad.</p><p>Plant species to see include prairie dock, big bluestem, foxglove beardtongue, golden alexander. Blooming times will vary so don&#39;t forget to check the &ldquo;Whats in Bloom&rdquo; board at the Welcome Center for up-to-date in-bloom info! Take the Henslow Trail to walk in and see this incredible restoration.</p>", "RECPORTAL_UNIT_KEY": "57092", "FORESTORGCODE": "0915", "OBJECTID": 37682793, "FEEDESCRIPTION": null, "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "Y", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "open" }, "geometry": { "type": "Point", "coordinates": [ -88.17156985582686, 41.34133573116096 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Chicago Road Seedbed", "LONGITUDE": "-88.077602", "LATITUDE": "41.393737", "RECAREAURL": "https://www.fs.usda.gov/recarea/midewin/recarea/?recid=82171", "OPEN_SEASON_START": "January 1", "OPEN_SEASON_END": "December 31", "FORESTNAME": "Midewin National Tallgrass Prairie", "RECAREAID": 82171, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016602.png", "MARKERACTIVITY": "Viewing Scenery", "MARKERACTIVITYGROUP": "Nature Viewing", "RECAREADESCRIPTION": "<p>Like most of Illinois, very little of Midewin consists of natural prairie &ndash; less than 200 acres, scattered in little remnants across the site. To restore the remainder of Midewin to tallgrass prairie and other native habitats (nearly 20,000 acres) will take considerable time and plant materials, including seed.</p><p>Three seedbeds, at the Supervisor&rsquo;s Office, River Road and Chicago Road, provide the native plant seeds from over 100 species of prairie plants to help restore Midewin with native plants.</p><p>Plantings for this seedbed began in 1996, the year Midewin was created. It is the second largest native plant seedbed at 2 acres. The plantings are mostly native grasses and forbs surrounded by a fence to prevent deer browsing. It will take a walk or bicycle ride to visit these seedbeds, located one mile south of the Hoff Road Trailhead. There is a nice walking trail around Turtle Pond here, too.</p><p>Although some types of wild seed are available from specialized native plant nurseries, many are not. That&rsquo;s one major purpose of Midewin&rsquo;s three native seed production gardens -- to produce seeds of native grasses and wildflowers that we cannot get from other sources. Many of these plant species are not commercially available, or if available, not in the amounts we need to restore prairie to Midewin. Even with our own production of seed and plants, it will still take many decades to restore much of the native habitats to Midewin.</p><p>For more information on seed production and some <a href=\"https://www.fs.usda.gov/detail/midewin/landmanagement/resourcemanagement/?cid=STELPRDB5176370\">Frequently Asked Questions </a> visit the Land And Resources Management section of the website.</p>", "RECPORTAL_UNIT_KEY": "57092", "FORESTORGCODE": "0915", "OBJECTID": 37682794, "FEEDESCRIPTION": null, "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "open" }, "geometry": { "type": "Point", "coordinates": [ -88.077607833489935, 41.393744745415596 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Jorgen's Hollow Campground", "LONGITUDE": "-97.201452", "LATITUDE": "46.524634", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=81825", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 81825, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016657.png", "MARKERACTIVITY": "Campground Camping", "MARKERACTIVITYGROUP": "Camping & Cabins", "RECAREADESCRIPTION": "<p align=\"center\">Jorgen&rsquo;s Hollow Campground is located forty miles southwest of Fargo, North Dakota.&nbsp;Click <a href=\"http://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5445162.pdf\"><strong>here</strong></a> for a map of the Jorgen&rsquo;s Hollow Campground and Trails.</p><p>Jorgen&rsquo;s Hollow Campground has 14 primitive campsites nestled within the oak savanna.&nbsp;Seven of those sites allow campers to have horses and seven sites are designated for campers without horses.&nbsp;Each campsite has a graveled pad, with a picnic table and fire ring.&nbsp;&nbsp;</p><p>While at the campground, you can enjoy the area by hiking the <strong><a href=\"http://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5445162.pdf\">Oak Leaf </a></strong>or <a href=\"http://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5445162.pdf\"><strong>North Country National Scenic Trail</strong></a>, viewing wildlife, birding, identifying wildflowers, and many other activities.&nbsp; Trailheads are located in the campground.</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682795, "FEEDESCRIPTION": "$10 per night. Payments can be placed in the fee tube located at the entrance to the campground; payments must be made immediately upon selecting a site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": "First-come, first-served. <strong>No reservations</strong> are accepted.", "RESTRICTIONS": "Stay limit of 14 consecutive days. ", "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": "<p>All facilities are accessible.</p>", "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -97.20146109098711, 46.524641914961819 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Sather Lake Recreation Area", "LONGITUDE": "-103.807874", "LATITUDE": "47.672293", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79456", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79456, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016657.png", "MARKERACTIVITY": "Campground Camping", "MARKERACTIVITYGROUP": "Camping & Cabins", "RECAREADESCRIPTION": "<p>Enjoy the lake view from your spacious campsite, or enjoy fishing for Bass, Crappie, or Trout off the floating pier&nbsp;located in the day use loop.&nbsp;</p><p>&nbsp;</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682796, "FEEDESCRIPTION": "$10&nbsp;per night. Payments can be placed in the fee tube located at the entrance to the campground; payments must be made immediately upon selecting a site.", "OPERATIONAL_HOURS": "Open year round. Limited services before Memorial Day and after Labor Day.", "RESERVATION_INFO": "First-come, first-served.<strong> </strong>No&nbsp;reservations are accepted.", "RESTRICTIONS": "Stay limit of 14 consecutive days. Pack-it-in, pack-it-out. ", "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -103.807885048447716, 47.672300492942504 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Bennett Campground", "LONGITUDE": "-103.348667", "LATITUDE": "47.490278", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79459", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79459, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016657.png", "MARKERACTIVITY": "Campground Camping", "MARKERACTIVITYGROUP": "Camping & Cabins", "RECAREADESCRIPTION": "<p>Enjoy the peaceful serenity offered at this campground.</p><p>&nbsp;</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682797, "FEEDESCRIPTION": "$10&nbsp;per night. Payments can be placed in the fee tube located at the entrance to the campground; payments must be made immediately upon selecting a site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": "First-come, first-served.<strong> N<strong>o&nbsp;</strong>reservations </strong>are accepted.", "RESTRICTIONS": "Stay limit of 14 consecutive days.", "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -103.348677896273145, 47.490285514330566 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Magpie Campground", "LONGITUDE": "-103.473584", "LATITUDE": "47.308585", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79460", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79460, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016657.png", "MARKERACTIVITY": "Campground Camping", "MARKERACTIVITYGROUP": "Camping & Cabins", "RECAREADESCRIPTION": "<p>This campground has plenty of shaded areas during the heat of summer. A perfect assembly point for folks who plan to travel to Devil&rsquo;s Pass for the amazing view. The Ice Caves are just a short hike away from this campground as well!</p><p>&nbsp;</p><p>A Maah Daah Hey trailhead is located at this campground.</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682798, "FEEDESCRIPTION": "$10&nbsp;per night. Payments can be placed in the fee tube located at the entrance to the campground; payments must be made immediately upon selecting a site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": "First-come, first-served. <strong>No&nbsp;reservations </strong>are accepted.", "RESTRICTIONS": "Stay limit of 14 consecutive days.", "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -103.473594892758015, 47.308592483044869 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Elkhorn Campground", "LONGITUDE": "-103.669277", "LATITUDE": "47.228405", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79461", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79461, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016657.png", "MARKERACTIVITY": "Campground Camping", "MARKERACTIVITYGROUP": "Camping & Cabins", "RECAREADESCRIPTION": "<p style=\"margin: 0in 0in 0pt;\">Enjoy the breathtaking view of a scenic canyon from this campground.</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682799, "FEEDESCRIPTION": "$10&nbsp;per night. Payments can be placed in the fee tube located at the entrance to the campground; payments must be made immediately upon selecting a site.<br />\r\n&nbsp;", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": "First-come, first-served. <strong>No reservations </strong>are accepted.", "RESTRICTIONS": "Stay limit of 14 consecutive days.", "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -103.669287926754905, 47.22841245669855 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Whitetail Picnic Area", "LONGITUDE": "-103.303293", "LATITUDE": "47.197931", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79464", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79464, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016657.png", "MARKERACTIVITY": "Campground Camping", "MARKERACTIVITYGROUP": "Camping & Cabins", "RECAREADESCRIPTION": "<p>Whitetail Picnic Area is a 10-unit picnic ground nestled in the densely wooded area of Whitetail Creek Drainage. Fire grates are available and a vault toilet. There is ample parking space available for most sizes of&nbsp;vehicle.</p><p>Be aware that the road to the picnic area crosses Whitetail Creek via a low water crossing that may be impassable during periods of high runoff.</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682800, "FEEDESCRIPTION": null, "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -103.303303828396196, 47.197938485849946 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Little Missouri National Grassland", "LONGITUDE": "-103.524722", "LATITUDE": "46.913333", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79469", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79469, "MARKERTYPE": "/Internet/FSE_MEDIA/stelprdb5166400.png", "MARKERACTIVITY": "Forest Service Shield", "MARKERACTIVITYGROUP": "Forest Service Shield", "RECAREADESCRIPTION": "<p>Little Missouri National Grassland is located in western North Dakota, USA. At 1,033,271 acres (418,150 ha), it is the largest grassland in the country.[1] Enclaved within its borders is Theodore Roosevelt National Park, which is managed by the National Park Service (and therefore not included in the preceding statistics). The Little Missouri National Grassland was once a part of the Custer National Forest, but is now a part of the Dakota Prairie Grasslands, a National Forest unit consisting entirely of &nbsp;National Grasslands. A predominant feature of the grassland is colorful and beautiful badlands and rugged terrain extensively eroded by wind and water. It is a mixed grass prairie, meaning it has both long and short grass.</p><p>The boundaries of the grasslands on certain maps can be misleading. Within the boundaries of the national grassland are significant portions of state-owned and privately owned land, much of it leased by cattle ranchers for grazing. Overall, in descending order of land area, it is located in parts of McKenzie, Billings, Slope, and Golden Valley counties.</p><p>White Butte, North Dakota&#39;s highest point, is located in the extreme southeast corner of the grassland, south of the town of Amidon.</p><p>The grassland is administered by USDA Forest Service as part of the Dakota Prairie Grasslands from offices in Bismarck, North Dakota. There are local ranger district offices in Dickinson and Watford City.</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682801, "FEEDESCRIPTION": null, "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -103.524732830467357, 46.913340434327345 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Cedar River National Grassland", "LONGITUDE": "-101.844300", "LATITUDE": "45.955200", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79471", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79471, "MARKERTYPE": "/Internet/FSE_MEDIA/stelprdb5166400.png", "MARKERACTIVITY": "Forest Service Shield", "MARKERACTIVITYGROUP": "Forest Service Shield", "RECAREADESCRIPTION": "<p>Cedar River National Grassland is located in Sioux County and Grant County in southern North Dakota, United States. It has a land area of 6,717 acres (2,718 ha). The portion in Sioux County lies within the Standing Rock Indian Reservation. Within the grassland are topographic features such as level plains and rolling hills. Dry streams and some small flowing streams exist throughout the grasslands.</p><p><br />The grassland is administered by the Forest Service as part of the Dakota Prairie Grasslands from offices in Bismarck, North Dakota. There are local ranger district offices (shared with Grand River National Grassland) in Lemmon, South Dakota.</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682802, "FEEDESCRIPTION": null, "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -101.844310231422043, 45.955207466688059 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Initial Rock", "LONGITUDE": "-103.411657", "LATITUDE": "46.807410", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79475", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79475, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016863.png", "MARKERACTIVITY": "Interpretive Areas", "MARKERACTIVITYGROUP": "Outdoor Learning", "RECAREADESCRIPTION": "<p>Custer&#39;s three camps are marked along the way, and at one camp on the evening of&nbsp;May 28, 1876, the initials of&nbsp; two of the privates were carved on a sandstone boulder now known as Initial Rock. This was Custer&#39;s one-way route to his demise at the Battle of the Little Bighorn.</p><p>&nbsp;</p><div>W.C. Williams, Company H, and F. Neely, Company M,</div><div>who left their initials in the sandstone rock, were with the expedition.</div>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682803, "FEEDESCRIPTION": null, "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "Y", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -103.411667782179919, 46.807417432312526 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Buffalo Gap Campground", "LONGITUDE": "-103.673706", "LATITUDE": "46.954980", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79452", "OPEN_SEASON_START": "All year (limited services in winter)", "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79452, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016657.png", "MARKERACTIVITY": "Campground Camping", "MARKERACTIVITYGROUP": "Camping & Cabins", "RECAREADESCRIPTION": "<link href=\"http://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5369461.css\" media=\"screen\" rel=\"stylesheet\" type=\"text/css\" /><style type=\"text/css\">#slider{border:0}</style><script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js\" type=\"text/javascript\"></script><script src=\"http://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5317644.js\" type=\"text/javascript\"></script><script type=\"text/javascript\">$(window).load(function(){$(\"#slider\").nivoSlider({effect:\"fade\",animSpeed:700,pauseTime:8000,randomStart:true,directionNav:true,controlNav:false})});</script><p>Buffalo Gap Campground features many amenities for an enjoyable camping experience.&nbsp;A camp host is on site from Memorial Day to Labor Day.</p><p>&nbsp;</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682804, "FEEDESCRIPTION": "$20&nbsp;per night. Payments can be placed in the fee tube located at the entrance to the campground; payments must be made immediately upon selecting a site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": "A limited number of campsites are available for reservations, all others are first-come, first-served. To reserve a campsite visit https://www.recreation.gov/camping/campgrounds/246796", "RESTRICTIONS": "Stay limit of 14 consecutive days. Horses are not allowed in the campground. ", "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -103.673716875784535, 46.954987425841779 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "CCC Campground", "LONGITUDE": "-103.276520", "LATITUDE": "47.587142", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79454", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79454, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016579.png", "MARKERACTIVITY": "Campground Camping", "MARKERACTIVITYGROUP": "Camping & Cabins", "RECAREADESCRIPTION": "<p>This newly remodeled campground is a favorite among Maah Daah Hey Trail users.</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682805, "FEEDESCRIPTION": "$10&nbsp;per night. Payments can be placed in the fee tube located at the entrance to the campground; payments must be made immediately upon selecting a site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": "a limited number of campsites are available for reservations, all others are first-come, first-served. To reserve a camping site go to https://www.recreation.gov/camping/campgrounds/10134015", "RESTRICTIONS": "Stay limit of 14 consecutive days.", "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -103.276530896828731, 47.587149531489267 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Summit Campground", "LONGITUDE": "-103.241504", "LATITUDE": "47.539961", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79455", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79455, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016657.png", "MARKERACTIVITY": "Campground Camping", "MARKERACTIVITYGROUP": "Camping & Cabins", "RECAREADESCRIPTION": "<p>There are two walk-in tent sites with picnic tables and fire grates. There are also two picnic areas with shelters and pull through camping units for RV&#39;s and other vehicles. The campground has a handicap accessible vault toilet.</p><p>A 100-yd hiking trail leading west from the campground&nbsp;provides visitors with &nbsp;a scenic view of&nbsp; the underlying valley.&nbsp;Summit trailhead is in the north end of the campground on the west side of the road. The campground has sufficient parking space that can also be used&nbsp;as a meeting point for Summit Trail.</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682806, "FEEDESCRIPTION": null, "OPERATIONAL_HOURS": null, "RESERVATION_INFO": null, "RESTRICTIONS": null, "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -103.24151487868582, 47.539968529412093 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Burning Coal Vein Campground", "LONGITUDE": "-103.443906", "LATITUDE": "46.597678", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79457", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79457, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016657.png", "MARKERACTIVITY": "Campground Camping", "MARKERACTIVITYGROUP": "Camping & Cabins", "RECAREADESCRIPTION": "<p style=\"margin: 0in 0in 0pt;\">Enjoy the scenic lookout from the Columnar Juniper area or the Ponderosa Pines just south and west of the campground.</p><p>&nbsp;</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682807, "FEEDESCRIPTION": "$10 per night. Payments can be placed in the fee tube located at the entrance to the campground; payments must be made immediately upon selecting a site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": "First-come, first-served. <strong>No reservations </strong>are accepted.", "RESTRICTIONS": "Stay limit of 14 consecutive days. No livestock facilities.", "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -103.443916751516227, 46.597685405642331 ] } },
    { "type": "Feature", "properties": { "RECAREANAME": "Wannagan Campground", "LONGITUDE": "-103.587853", "LATITUDE": "47.055184", "RECAREAURL": "https://www.fs.usda.gov/recarea/dpg/recarea/?recid=79463", "OPEN_SEASON_START": null, "OPEN_SEASON_END": null, "FORESTNAME": "Dakota Prairie Grasslands", "RECAREAID": 79463, "MARKERTYPE": "/Internet/FSE_MEDIA/fsbdev2_016657.png", "MARKERACTIVITY": "Campground Camping", "MARKERACTIVITYGROUP": "Camping & Cabins", "RECAREADESCRIPTION": "<p>A great meeting area for the north end of the Buffalo Gap Trail. The switchbacks located on the Maah Daah Hey Trail offer a sweeping vista of the region, including a scenic view of many large buttes.</p>", "RECPORTAL_UNIT_KEY": "79451", "FORESTORGCODE": "0118", "OBJECTID": 37682808, "FEEDESCRIPTION": "$10 per night. Payments can be placed in the fee tube located at the entrance to the campground; payments must be made immediately upon selecting a site.", "OPERATIONAL_HOURS": null, "RESERVATION_INFO": "First-come, first-served. <strong>No reservations</strong> are accepted.", "RESTRICTIONS": "Stay limit of 14 consecutive days.", "INFRA_CN": null, "SPOTLIGHTDISPLAY": "N", "ATTRACTIONDISPLAY": "N", "ACCESSIBILITY": null, "OPENSTATUS": "none" }, "geometry": { "type": "Point", "coordinates": [ -103.587863873148976, 47.055191444657275 ] } } 
    ]})
    
    
console.log(dat)

// river data from here: https://catalog.data.gov/dataset/national-wild-and-scenic-river-active-study-rivers-lines-feature-layer-3d86c
// recreation opportunities from herer: https://catalog.data.gov/dataset/recreation-opportunities-feature-layer-69fe2

// get some info on the structure of the file
fetch('data/Recreation_Opportunities.geojson')
    .then(response => response.json())
    .then(data => {
        // Initialize summary object
        const summary = {
            totalFeatures: data.features.length,
            properties: {}
        };

        // Iterate through each feature
        data.features.forEach(feature => {
            // Extract properties of each feature
            const properties = feature.properties;

            // Iterate through each property
            for (const [key, value] of Object.entries(properties)) {
                // Initialize property in summary object if not already present
                if (!summary.properties[key]) {
                    summary.properties[key] = {
                        count: 1,
                        values: [value]
                    };
                } else {
                    // Update count and values array for the property
                    summary.properties[key].count++;
                    summary.properties[key].values.push(value);
                }
            }
        });

        // Print summary to console
        console.log('Summary:', summary);
    })
    .catch(error => console.error('Error fetching or parsing GeoJSON:', error));


    var map = L.map('map').setView([32, -84], 4);
// helpful locate control info: https://www.jsdelivr.com/package/npm/leaflet.locatecontrol
// potential info for filter by location: https://handsondataviz.org/leaflet-searchable-map.html
    L.control.locate().addTo(map);
// map.locate({setView: true, maxZoom: 16});
// function onLocationFound(e) {
//     var radius = e.accuracy;

//     L.marker(e.latlng).addTo(map)
//         .bindPopup("You are within " + radius + " meters from this point").openPopup();

//     L.circle(e.latlng, radius).addTo(map);
// }
// function onLocationError(e) {
//     alert(e.message);
// }

// map.on('locationerror', onLocationError);
// map.on('locationfound', onLocationFound);
// make the map
// this is the mapping object in memory

// hyperlinks from mapbox for style
// style url: mapbox://styles/warnekeb/clswrfll8002e01py3vvoerv4
// access token: pk.eyJ1Ijoid2FybmVrZWIiLCJhIjoiY2xzb3plZzh4MDAwdzJqczNjYnJxY3Y3dyJ9.KAtMBP36gpid7pf25U1BXQ
// template: https://api.mapbox.com/styles/v1/YOUR_USERNAME/YOUR_STYLE_ID/tiles/256/{z}/{x}/{y}?access_token=YOUR_MAPBOX_ACCESS_TOKEN

L.tileLayer('https://api.mapbox.com/styles/v1/warnekeb/clswrfll8002e01py3vvoerv4/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoid2FybmVrZWIiLCJhIjoiY2xzb3plZzh4MDAwdzJqczNjYnJxY3Y3dyJ9.KAtMBP36gpid7pf25U1BXQ', {
maxZoom: 19
}).addTo(map);

  
const geojsonMarkerOptions = {
    radius: 8,
    fillColor: "#ff7800",
    color: "#000",
    weight: 1,
    opacity: 1,
    fillOpacity: 0.8
};

function extractProperties(geojson) {
    const propertiesList = [];

    geojson.features.forEach(feature => {
        propertiesList.push(feature.properties.MARKERACTIVITY);
    });

    return propertiesList;
}
var activities = extractProperties(dat);
console.log(activities);


// var markers = new L.MarkerClusterGroup();
//     L.geoJSON(dat, {
//                     pointToLayer: function (feature, latlng) {
//                         return markers.addLayer(L.circleMarker(latlng, geojsonMarkerOptions));
//                     },
//                     onEachFeature: function (feature, layer) {
//                         layer.bindPopup('Name: ' + feature.properties.RECAREANAME + '</b><br />' +
//                           'Activity: ' + feature.properties.MARKERACTIVITY+ '</b><br />' +
//                          'Link: '+  feature.properties.RECAREAURL )
//                         }, 
                                    
//         }
//                     ).addTo(map);
    var markers = [];
    dat.forEach(function(feature) {
      var marker = L.marker(feature.latlng).addTo(map);
      marker.bindPopup(feature.latlng);
      markers.push(marker);
    });
 // Function to filter markers based on distance from user's location
 function filterMarkers(userLocation, radius) {
    markers.forEach(function(marker) {
      var distance = userLocation.distanceTo(marker.getLatLng());
      if (distance > radius) {
        marker.addTo(map);
      } else {
        map.removeLayer(marker);
      }
    });
  }

  // Listen for when the user's location is found or updated
  map.on('locationfound', function(e) {
    var userLocation = e.latlng;
    var radius = e.accuracy / 2; // Use accuracy as radius (in meters)
    filterMarkers(userLocation, radius);
  });

  // Listen for location error
  map.on('locationerror', function(e) {
    alert("Location access denied.");
  });
// var group;
// var x;
// var y;
// var markers = new L.MarkerClusterGroup();
// y = fetch('data/Recreation_Opportunities.geojson')
//     .then(response => response.json())
//     .then(data => {
//         x =data;
//         L.geoJSON(data, {
//             pointToLayer: function (feature, latlng) {
//                 return markers.addLayer(L.circleMarker(latlng, geojsonMarkerOptions));
//             },
//             onEachFeature: function (feature, layer) {
//                 layer.bindPopup('Name: ' + feature.properties.RECAREANAME + '</b><br />' +
//                   'Activity: ' + feature.properties.MARKERACTIVITY+ '</b><br />' +
//                  'Link: '+  feature.properties.RECAREAURL )
//                 }, 
                            
// }
//             ).addTo(map);
//         }) 
//  console.log(x)

  //  map.addLayer(markers); <= this doesn't seem to be necessary



